env:
  id: "NewPasture-v2"
  base_kwargs:
    state_size: [256, 256]
    state_downsize: [256, 256]
    action_type: "continuous"
    use_trajectory: true
    boundary_source: "box"
    use_apf: true
    use_mist: true
    use_multiscale: true
    multiscale_feature_size: 32

scenes:
  weed_dists: ["gaussian"]
  seeds: [25]

  levels:
    - name: "easy"
      num_obstacles_range: [0, 0]
      weed_num: 50
      map_ids: [2]

methods:
  rules:
    - name: "BCP"
    - name: "SNAKE"
    - name: "R_SNAKE"
    - name: "JUMP"
    - name: "REACT"

eval:
  max_steps: 3000
  L_thresholds: [0.9, 0.95, 0.98]
  workers_rules: 4
  render_last_frame: true
  output_root: "rules_new/outputs_5alg_quick"
