device: null
pretrained_model: null
ckpt_name: area_coverage_v5_with_direction_field
seed: 42

# 12个场景的数据（V5使用更复杂的观测空间，可能需要更多训练）
# collector
collector:
  total_frames: 1_500_000  # 比V4稍多一些
  frames_per_batch: 20
  num_envs: 16
  init_random_frames: 30_000  # 比V4稍多一些

# buffer
buffer:
  buffer_size: 300_000  # 比V4稍大
  batch_size: 2048
  scratch_dir: /home/lzh/data/rl_buffers  # 临时文件存储路径

# Optim
optim:
  lr_critic: 3.0e-4
  weight_decay_critic: 0
  lr_actor: 1.0e-5
  weight_decay_actor: 1.0e-4
  lr_alpha: 3.0e-4
  weight_decay_alpha: 0
  max_grad_norm: null

# loss
loss:
  gamma: 0.99
  target_update_polyak: 0.9997
  target_entropy_weight: 0.2
  target_entropy: "auto"
  utd_ratio: 1
  loss_function: l2

# logger
logger:
  backend: wandb
  model_name: V5_SAC_with_direction_field
  exp_name: Train
  test_interval: 200_00